[workspace]
members = [
    "crates/types",
    "crates/sql-function-catalog",
    "crates/asap-aware-mapping",
    "crates/frontend-promql",
    "crates/frontend-metricsql",
    "crates/metricsql-common-parser-support",
    "crates/frontend-sql",
    "crates/devtools",
    "crates/integration-tests",
]
exclude = ["crates/metricsql-parser-vendored"]
resolver = "2"

[workspace.dependencies]
asap_sketchlib = { git = "https://github.com/ProjectASAP/asap_sketchlib", rev = "da3635a80f8f854d47b772d49d5a9e5fb6927d8e" }
