[package]
name = "asap-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
asap-types = { path = "../types" }
asap-frontend-promql = { path = "../frontend-promql" }
asap-frontend-sql = { path = "../frontend-sql" }
asap-aware-mapping = { path = "../asap-aware-mapping" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
