#!/usr/bin/env python3
"""Extract PromQL strings from the metrics-observability benchmark dump."""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

QUERY_LOG = re.compile(r'(?:query=|"query":)"((?:\\.|[^"\\])*)"')
YAML_EXPR = re.compile(
    r'^\s*(?:-\s*)?["\']?expr["\']?:[ \t]*(?P<expr>(?![ \t]*[|>]).*?)[ \t]*$', re.MULTILINE
)


def unique(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result = []
    for value in values:
        value = re.sub(r"\s+", " ", value).strip()
        if value and value not in seen:
            seen.add(value)
            result.append(value)
    return result


def from_log(path: Path) -> list[str]:
    return [bytes(value, "utf-8").decode("unicode_escape") for value in QUERY_LOG.findall(path.read_text())]


def from_json(path: Path) -> list[str]:
    values: list[str] = []
    document = json.loads(path.read_text())

    def visit(value: object) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key in {"expr", "expression", "query", "queryText"} and isinstance(child, str):
                    values.append(child)
                visit(child)
        elif isinstance(value, list):
            for child in value:
                visit(child)

    visit(document)
    return values


def from_yaml(path: Path) -> list[str]:
    lines = path.read_text().splitlines()
    values: list[str] = []
    index = 0
    while index < len(lines):
        match = YAML_EXPR.match(lines[index])
        if match:
            values.append(match.group("expr"))
        elif re.match(r'^\s*(?:-\s*)?["\']?expr["\']?:\s*[|>]', lines[index]):
            block = []
            index += 1
            while index < len(lines) and not lines[index].strip():
                block.append(lines[index])
                index += 1
            body_indent = len(lines[index]) - len(lines[index].lstrip()) if index < len(lines) else 0
            while index < len(lines):
                indent = len(lines[index]) - len(lines[index].lstrip())
                if lines[index].strip() and indent < body_indent:
                    break
                block.append(lines[index])
                index += 1
            nonempty = [line for line in block if line.strip()]
            indent = min((len(line) - len(line.lstrip()) for line in nonempty), default=0)
            values.append(
                " ".join(
                    line[indent:].strip()
                    for line in block
                    if line.strip() and not line[indent:].lstrip().startswith("#")
                ).strip()
            )
            continue
        index += 1
    return values


def from_csv(path: Path) -> list[str]:
    with path.open(newline="") as stream:
        rows = csv.DictReader(stream)
        return [row["PromQL"] for row in rows if row.get("PromQL")]


def extract(paths: list[Path]) -> list[str]:
    values: list[str] = []
    for path in paths:
        if path.suffix == ".log":
            values.extend(from_log(path))
        elif path.suffix == ".json":
            values.extend(from_json(path))
        elif path.suffix in {".yml", ".yaml"}:
            values.extend(from_yaml(path))
        elif path.suffix == ".csv":
            values.extend(from_csv(path))
    return unique(values)


def write_fixture(output: Path, name: str, paths: list[Path]) -> None:
    queries = extract(paths)
    output.joinpath(f"{name}.txt").write_text(
        "# Generated by tools/metrics_observability/extract_promql.py\n"
        + "\n".join(queries)
        + "\n"
    )
    print(f"{name}: {len(queries)} queries from {len(paths)} files")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("benchmark_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    root = args.benchmark_root / "queries"
    args.output.mkdir(parents=True, exist_ok=True)

    write_fixture(args.output, "cmu_chad_logs", sorted((root / "cmu_chad").glob("*.log")))
    write_fixture(args.output, "cmu_chad_dashboards", sorted((root / "cmu_chad/grafana_dashboards/dashboards").glob("*.json")))
    write_fixture(args.output, "cmu_chad_rules", sorted((root / "cmu_chad").rglob("*.yaml")))
    write_fixture(args.output, "from_claude_logs", sorted((root / "from-claude").glob("*.log")))
    write_fixture(args.output, "grafana_dashboards", sorted((root / "grafana_dashboards").glob("*.json")))
    write_fixture(args.output, "kubernetes_mixin_dashboards", sorted((root / "kubernetes-mixin/dashboards_out").glob("*.json")))
    write_fixture(args.output, "kubernetes_mixin_alerts", [root / "kubernetes-mixin/prometheus_alerts.yaml"])
    write_fixture(args.output, "kubernetes_mixin_rules", [root / "kubernetes-mixin/prometheus_rules.yaml"])
    write_fixture(args.output, "promset", sorted((root / "kaggle_promeset").rglob("*.csv")))


if __name__ == "__main__":
    main()
