use asap_frontend_metricsql::{canonical_metricsql, parse_metricsql};
use metricsql_parser::ast::{Expr, Operator};

/// Direct canonical outputs generated by the official VictoriaMetrics Go
/// parser `github.com/VictoriaMetrics/metricsql` v0.84.4. The expected side is
/// deliberately not parsed by Rust, so one Rust parser bug cannot affect both
/// sides of the assertion.
const OFFICIAL_GO_GOLDEN: &[(&str, &str)] = &[
    (r#"foo{job="a" or job="b"}"#, r#"foo{job="a" or job="b"}"#),
    (
        r#"WITH (prefix="http_") {__name__=prefix+"requests_total"}"#,
        "http_requests_total",
    ),
    (
        "WITH (x = rate(foo[5m])) sum(x) by (job)",
        "sum(rate(foo[5m])) by(job)",
    ),
    (
        r#"sum(rate(foo{code!="500",env=~"prod|staging"}[5m])) by (job) limit 10"#,
        r#"sum(rate(foo{code!="500", env=~"prod|staging"}[5m])) by(job) limit 10"#,
    ),
    (
        "rate(foo[5i]) keep_metric_names",
        "rate(foo[5i]) keep_metric_names",
    ),
];

#[test]
fn official_victoriametrics_corpus_matches_direct_canonical_output() {
    for &(query, official) in OFFICIAL_GO_GOLDEN {
        let actual = canonical_metricsql(query).unwrap_or_else(|error| {
            panic!("Rust parser rejected official input {query:?}: {error}")
        });
        assert_eq!(
            strip_formatting_whitespace(&actual),
            strip_formatting_whitespace(official),
            "query: {query}"
        );
    }
}

fn strip_formatting_whitespace(value: &str) -> String {
    let mut quoted = false;
    let mut escaped = false;
    let compact: String = value
        .chars()
        .filter(|&ch| {
            if quoted && ch == '\\' && !escaped {
                escaped = true;
                return true;
            }
            if ch == '"' && !escaped {
                quoted = !quoted;
            }
            escaped = false;
            quoted || !ch.is_whitespace()
        })
        .collect();
    let mut normalized = String::with_capacity(compact.len());
    let mut rest = compact.as_str();
    while let Some(open) = rest.find('{') {
        let (prefix, after_open) = rest.split_at(open + 1);
        normalized.push_str(prefix);
        let Some(close) = after_open.find('}') else {
            normalized.push_str(after_open);
            return normalized;
        };
        let (matchers, suffix) = after_open.split_at(close);
        if matchers.contains("or") {
            normalized.push_str(matchers);
        } else {
            let mut fields: Vec<_> = matchers.split(',').collect();
            fields.sort_unstable();
            normalized.push_str(&fields.join(","));
        }
        normalized.push('}');
        rest = &suffix[1..];
    }
    normalized.push_str(rest);
    normalized
}

#[test]
fn official_extension_cases_preserve_typed_ast_semantics() {
    let conditional = parse_metricsql("time() ifnot time() > 1400 default -time()").unwrap();
    assert!(
        matches!(conditional, Expr::BinaryOperator(ref binary) if binary.op == Operator::Default)
    );

    let matched = parse_metricsql("foo + on(job) group_left(instance) bar").unwrap();
    assert!(
        matches!(matched, Expr::BinaryOperator(ref binary) if binary.op == Operator::Add && binary.modifier.is_some())
    );

    let offset = parse_metricsql("foo offset 1.5h").unwrap();
    assert!(matches!(offset, Expr::Rollup(ref rollup) if rollup.offset.is_some()));
}

#[test]
fn official_victoriametrics_numeric_tokens_have_the_expected_value() {
    let ast = parse_metricsql("1_000 + 0x10 + 2.5Mi")
        .expect("Rust parser must accept VictoriaMetrics numeric tokens");
    assert_eq!(eval_numeric(&ast), Some(2_622_456.0));
}

fn eval_numeric(expr: &Expr) -> Option<f64> {
    match expr {
        Expr::NumberLiteral(number) => Some(number.value),
        Expr::Parens(parens) if parens.expressions.len() == 1 => {
            eval_numeric(&parens.expressions[0])
        }
        Expr::UnaryOperator(unary) => eval_numeric(&unary.expr).map(|value| -value),
        Expr::BinaryOperator(binary) => {
            let left = eval_numeric(&binary.left)?;
            let right = eval_numeric(&binary.right)?;
            match binary.op {
                Operator::Add => Some(left + right),
                Operator::Sub => Some(left - right),
                Operator::Mul => Some(left * right),
                Operator::Div => Some(left / right),
                Operator::Mod => Some(left % right),
                Operator::Pow => Some(left.powf(right)),
                _ => None,
            }
        }
        _ => None,
    }
}
