//! Unit- and provenance-aware cost annotations for exported DAGs.
//!
//! This crate defines the interchange schema; it does not estimate costs.
//! Producers may report a horizon total, a recurring rate, or no value.
//! Values with different [`CostUnit`]s are
//! never combined. A missing estimate is represented by
//! [`CostAnnotation::unavailable`], never by zero.
//!
//! A baseline comparison uses `delta = baseline_value - selected_value` and,
//! when `baseline_value > 0`, `benefit_ratio = delta / baseline_value`.
//! Model inputs and a model version (or a benchmark identifier for measured
//! values) keep every emitted number auditable.

use serde::{Deserialize, Serialize};

/// The unit one [`CostAnnotation::value`] (and its `delta`) is expressed in.
/// Producers and consumers must not compare or aggregate different units.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CostUnit {
    /// A recurring cost expressed per second (`cost_units / s`) — the
    /// recurring costs. It requires an explicit recurrence interval/rate.
    CostUnitsPerSecond,
    /// A finite-run or one-shot total at some horizon `H` — `total_cost(H)`
    /// in the issue's formulas, or a standalone one-shot addend. Never
    /// aggregated with [`CostUnitsPerSecond`](CostUnit::CostUnitsPerSecond)
    /// except through [`total_cost`], which keeps the two terms explicit
    /// rather than silently adding a rate to a total.
    CostUnits,
}

impl std::fmt::Display for CostUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CostUnit::CostUnitsPerSecond => write!(f, "cost units/s"),
            CostUnit::CostUnits => write!(f, "cost units"),
        }
    }
}

/// Provenance of one [`CostAnnotation`]'s value — the issue's three states.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CostSource {
    /// Generated by a named/versioned cost model
    /// ([`CostAnnotation::model_version`]).
    Modeled,
    /// Loaded from a reproducible benchmark artifact
    /// ([`CostAnnotation::benchmark_id`]) — issue #288.
    Measured,
    /// No value. `value` is always `None` for this source — never encode an
    /// unknown value as `0` or another synthetic number.
    Unavailable,
}

/// What a [`CostAnnotation`]'s `baseline`/`delta`/`benefit_ratio` are
/// measured against. The issue names two examples explicitly; both are
/// first-class variants here rather than opaque strings so a renderer can
/// display them without guessing. [`Named`](BaselineRef::Named) covers any
/// other explicitly-chosen baseline a future caller introduces.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "detail")]
pub enum BaselineRef {
    /// Recomputing the pre-ASAP target independently at every consumer site
    /// — "do nothing" (never apply ASAP-aware replacement at all).
    PreAsapRecomputation,
    /// The best-ranked *non-selected* legal candidate for the same target
    /// (`rank` into that target's own `PlanSpace::cost_sorted` ordering,
    /// `0` = best; a baseline referencing this variant is always `rank >=
    /// 1`, since `rank 0` is what got selected).
    HighestRankedNonSelectedCandidate { rank: usize },
    /// Any other explicitly-named baseline.
    Named(String),
}

/// One raw input that fed a [`CostAnnotation`]'s `value` — surfaced so the
/// viewer's sidebar can show *why* a modeled number is what it is, not just
/// the number itself.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CostInput {
    pub name: String,
    pub value: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl CostInput {
    pub fn new(name: impl Into<String>, value: f64) -> Self {
        CostInput {
            name: name.into(),
            value,
            unit: None,
        }
    }
}

/// A structured, optional cost/benefit annotation — issue #286's schema.
/// Every numeric value carries units and provenance; a missing value is
/// [`CostSource::Unavailable`] with `value: None`, never a fabricated
/// number. See the module doc for the exact formulas this backs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CostAnnotation {
    pub value: Option<f64>,
    pub unit: CostUnit,
    pub source: CostSource,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baseline: Option<BaselineRef>,
    /// `baseline_value - value` under `baseline`, when both are known — the
    /// corresponding benefit in this annotation's declared unit.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta: Option<f64>,
    /// `delta / baseline_value`, when `baseline_value > 0` — the issue's
    /// `estimated_benefit_ratio`. Not part of the issue's own sketch schema
    /// verbatim (the issue only asks that ratio be *derivable*), but kept
    /// as its own explicit field rather than pushed onto the caller to
    /// recompute from `delta` plus a `baseline` it would otherwise have no
    /// value for.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub benefit_ratio: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub benchmark_id: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub inputs: Vec<CostInput>,
}

impl CostAnnotation {
    /// No value at all — `value: None`, `source: Unavailable`. `unit` is
    /// still required: it states what unit a value *would* have been in,
    /// had one been available, so a renderer can group "not estimated"
    /// alongside the kind of number it's missing.
    pub fn unavailable(unit: CostUnit) -> Self {
        CostAnnotation {
            value: None,
            unit,
            source: CostSource::Unavailable,
            baseline: None,
            delta: None,
            benefit_ratio: None,
            model_version: None,
            benchmark_id: None,
            inputs: Vec::new(),
        }
    }

    /// A modeled value with no baseline comparison attached yet — chain
    /// [`with_baseline`](Self::with_baseline) to add one.
    pub fn modeled(
        value: f64,
        unit: CostUnit,
        model_version: impl Into<String>,
        inputs: Vec<CostInput>,
    ) -> Self {
        CostAnnotation {
            value: Some(value),
            unit,
            source: CostSource::Modeled,
            baseline: None,
            delta: None,
            benefit_ratio: None,
            model_version: Some(model_version.into()),
            benchmark_id: None,
            inputs,
        }
    }

    /// Attach `baseline` plus its own value, computing `delta` and
    /// [`benefit_ratio`](Self::benefit_ratio) per the issue's formulas.
    /// `self.value` must already be `Some` (an
    /// [`unavailable`](Self::unavailable) annotation has nothing to
    /// subtract a baseline from and is returned unchanged).
    pub fn with_baseline(mut self, baseline: BaselineRef, baseline_value: f64) -> Self {
        let Some(value) = self.value else {
            return self;
        };
        let delta = baseline_value - value;
        self.delta = Some(delta);
        self.benefit_ratio = benefit_ratio(baseline_value, delta);
        self.baseline = Some(baseline);
        self
    }
}

/// `delta / baseline_value`, or `None` when `baseline_value <= 0` — the
/// issue's explicit "ratio unavailable" guard (a zero or negative baseline
/// makes a ratio meaningless, not just numerically awkward).
pub fn benefit_ratio(baseline_value: f64, delta: f64) -> Option<f64> {
    if baseline_value > 0.0 {
        Some(delta / baseline_value)
    } else {
        None
    }
}

/// `total_cost(H) = recurring_cost_rate * H + one_shot_cost` — finite-run or
/// one-shot totals require an explicit horizon. Returns `None` (never a
/// fabricated or poisoned total) when both terms are `None`, when `horizon`
/// isn't a finite, non-negative number for a `Some(rate)`, or when either
/// `recurring_cost_rate` or `one_shot_cost` is itself non-finite (`NaN` or
/// infinite) — a non-finite input must never silently produce `Some(NaN)`.
/// Rate and one-shot costs are passed as separate arguments specifically so
/// they can never be silently added by a caller before this function ever
/// sees them.
pub fn total_cost(
    recurring_cost_rate: Option<f64>,
    horizon: f64,
    one_shot_cost: Option<f64>,
) -> Option<f64> {
    // A non-finite input anywhere here (NaN/±inf — e.g. from a future #287
    // caller upstream) must never quietly poison the total into `Some(NaN)`:
    // that would violate this module's own "never fabricate, never a
    // poisoned total" rule as much as inventing a number from nothing would.
    if let Some(rate) = recurring_cost_rate {
        if !rate.is_finite() {
            return None;
        }
    }
    if let Some(one_shot) = one_shot_cost {
        if !one_shot.is_finite() {
            return None;
        }
    }
    let recurring = match recurring_cost_rate {
        Some(rate) => {
            if !horizon.is_finite() || horizon < 0.0 {
                return None;
            }
            rate * horizon
        }
        None => 0.0,
    };
    match (recurring_cost_rate, one_shot_cost) {
        (None, None) => None,
        _ => Some(recurring + one_shot_cost.unwrap_or(0.0)),
    }
}

/// Two [`CostAnnotation`]s were summed by [`sum_workload_costs`] despite
/// disagreeing on [`CostUnit`] — unit-incompatible aggregation is rejected
/// rather than silently mixed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnitMismatch {
    pub first: CostUnit,
    pub second: CostUnit,
}

impl std::fmt::Display for UnitMismatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "cannot aggregate cost annotations with mismatched units: {} vs {}",
            self.first, self.second
        )
    }
}
impl std::error::Error for UnitMismatch {}

/// Sum a workload's per-node cost annotations into one workload-wide total,
/// counting each distinct `workload_node_id` exactly once — the "shared
/// nodes must be counted once in workload totals" requirement. `entries` is
/// `(workload_node_id, annotation)` pairs; an entry with `workload_node_id:
/// None` is never deduplicated against anything else (each is its own,
/// always-unique contribution). If any distinct entry has no value, the
/// aggregate is unavailable as well: returning a numeric subtotal would
/// misrepresent it as the whole workload's cost.
///
/// Rejects the sum with [`UnitMismatch`] the moment two distinct entries
/// disagree on [`CostUnit`] — "unit-incompatible aggregation is rejected".
pub fn sum_workload_costs<'a, I>(entries: I) -> Result<CostAnnotation, UnitMismatch>
where
    I: IntoIterator<Item = (Option<u32>, &'a CostAnnotation)>,
{
    let mut seen_ids = std::collections::HashSet::new();
    let mut unit: Option<CostUnit> = None;
    let mut total = 0.0_f64;
    let mut counted_any = false;
    let mut missing_any = false;
    let mut model_versions: Vec<String> = Vec::new();

    for (workload_node_id, annotation) in entries {
        if let Some(id) = workload_node_id {
            if !seen_ids.insert(id) {
                continue; // already counted this shared node once
            }
        }
        match unit {
            None => unit = Some(annotation.unit),
            Some(existing) if existing != annotation.unit => {
                return Err(UnitMismatch {
                    first: existing,
                    second: annotation.unit,
                });
            }
            _ => {}
        }
        let Some(value) = annotation.value else {
            missing_any = true;
            continue;
        };
        total += value;
        counted_any = true;
        if let Some(version) = &annotation.model_version {
            if !model_versions.contains(version) {
                model_versions.push(version.clone());
            }
        }
    }

    Ok(if counted_any && !missing_any {
        CostAnnotation {
            value: Some(total),
            unit: unit.expect("counted_any implies unit was set"),
            source: CostSource::Modeled,
            baseline: None,
            delta: None,
            benefit_ratio: None,
            model_version: if model_versions.len() == 1 {
                Some(model_versions.remove(0))
            } else {
                None
            },
            benchmark_id: None,
            inputs: Vec::new(),
        }
    } else {
        CostAnnotation::unavailable(unit.unwrap_or(CostUnit::CostUnits))
    })
}

/// Whole-selected-workload cost/benefit — one query's (or one workload
/// batch's) aggregate baseline, selected, and benefit, built from
/// [`sum_workload_costs`] over that scope's own per-decision node
/// annotations. See [`crate::dag_export::NamedGraph::workload_cost`] /
/// [`crate::dag_export::WorkloadGraph::workload_cost`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkloadCostSummary {
    pub baseline_cost: CostAnnotation,
    pub selected_cost: CostAnnotation,
    pub benefit: CostAnnotation,
}

/// Build a [`WorkloadCostSummary`] from one `(workload_node_id, baseline,
/// selected)` triple per decision node in scope — see
/// [`WorkloadCostSummary`]'s own doc. `model_version` labels the resulting
/// `benefit` annotation.
pub fn workload_cost_summary<'a, I>(
    entries: I,
    model_version: impl Into<String>,
) -> Result<WorkloadCostSummary, UnitMismatch>
where
    I: IntoIterator<Item = (Option<u32>, &'a CostAnnotation, &'a CostAnnotation)> + Clone,
{
    let baseline_cost = sum_workload_costs(
        entries
            .clone()
            .into_iter()
            .map(|(id, baseline, _)| (id, baseline)),
    )?;
    let selected_cost =
        sum_workload_costs(entries.into_iter().map(|(id, _, selected)| (id, selected)))?;

    let benefit = match (baseline_cost.value, selected_cost.value) {
        (Some(baseline_value), Some(selected_value))
            if baseline_cost.unit == selected_cost.unit =>
        {
            let delta = baseline_value - selected_value;
            CostAnnotation {
                value: Some(delta),
                unit: selected_cost.unit,
                source: CostSource::Modeled,
                baseline: Some(BaselineRef::PreAsapRecomputation),
                delta: None,
                benefit_ratio: benefit_ratio(baseline_value, delta),
                model_version: Some(model_version.into()),
                benchmark_id: None,
                inputs: Vec::new(),
            }
        }
        (Some(_), Some(_)) => {
            return Err(UnitMismatch {
                first: baseline_cost.unit,
                second: selected_cost.unit,
            })
        }
        _ => CostAnnotation::unavailable(selected_cost.unit),
    };

    Ok(WorkloadCostSummary {
        baseline_cost,
        selected_cost,
        benefit,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unavailable_has_no_value_and_no_synthetic_number() {
        let a = CostAnnotation::unavailable(CostUnit::CostUnits);
        assert_eq!(a.value, None);
        assert_eq!(a.source, CostSource::Unavailable);
    }

    #[test]
    fn with_baseline_computes_delta_and_ratio() {
        let a = CostAnnotation::modeled(3.0, CostUnit::CostUnits, "v1", vec![])
            .with_baseline(BaselineRef::PreAsapRecomputation, 10.0);
        assert_eq!(a.delta, Some(7.0));
        assert_eq!(a.benefit_ratio, Some(0.7));
        assert_eq!(a.baseline, Some(BaselineRef::PreAsapRecomputation));
    }

    #[test]
    fn benefit_ratio_unavailable_when_baseline_not_positive() {
        assert_eq!(benefit_ratio(0.0, 5.0), None);
        assert_eq!(benefit_ratio(-1.0, 5.0), None);
        assert_eq!(benefit_ratio(2.0, 1.0), Some(0.5));
    }

    #[test]
    fn with_baseline_on_unavailable_annotation_is_a_no_op() {
        let a = CostAnnotation::unavailable(CostUnit::CostUnits)
            .with_baseline(BaselineRef::PreAsapRecomputation, 10.0);
        assert_eq!(a.value, None);
        assert_eq!(a.delta, None);
        assert_eq!(a.baseline, None);
    }

    #[test]
    fn total_cost_requires_a_horizon_for_a_recurring_rate() {
        assert_eq!(total_cost(Some(2.0), 5.0, None), Some(10.0));
        assert_eq!(total_cost(Some(2.0), 5.0, Some(1.0)), Some(11.0));
        assert_eq!(total_cost(None, 5.0, Some(4.0)), Some(4.0));
        assert_eq!(total_cost(None, 5.0, None), None);
    }

    #[test]
    fn total_cost_rejects_a_non_finite_or_negative_horizon() {
        assert_eq!(total_cost(Some(2.0), f64::NAN, None), None);
        assert_eq!(total_cost(Some(2.0), f64::INFINITY, None), None);
        assert_eq!(total_cost(Some(2.0), -1.0, None), None);
    }

    /// A non-finite `recurring_cost_rate` (e.g. a stray `NaN` from a future
    /// #287 caller) must never silently produce `Some(NaN)` — that's a
    /// poisoned total, exactly the kind of fabricated-looking value this
    /// module's "never fabricate" rule exists to prevent.
    #[test]
    fn total_cost_rejects_a_non_finite_recurring_rate() {
        assert_eq!(total_cost(Some(f64::NAN), 5.0, None), None);
        assert_eq!(total_cost(Some(f64::INFINITY), 5.0, None), None);
        assert_eq!(total_cost(Some(f64::NEG_INFINITY), 5.0, Some(1.0)), None);
    }

    /// Same guard on the one-shot addend — a `NaN`/infinite one-shot cost
    /// must not poison the total either, even when the recurring side is
    /// perfectly well-formed.
    #[test]
    fn total_cost_rejects_a_non_finite_one_shot_cost() {
        assert_eq!(total_cost(Some(2.0), 5.0, Some(f64::NAN)), None);
        assert_eq!(total_cost(None, 5.0, Some(f64::INFINITY)), None);
    }

    fn ann(value: f64, unit: CostUnit) -> CostAnnotation {
        CostAnnotation::modeled(value, unit, "v1", vec![])
    }

    #[test]
    fn sum_workload_costs_counts_a_shared_node_once() {
        let a = ann(5.0, CostUnit::CostUnits);
        let b = ann(5.0, CostUnit::CostUnits);
        let c = ann(2.0, CostUnit::CostUnits);
        // Node id 1 shared by two queries (same decision, same cost) must
        // only be counted once; node id 2 is a distinct contribution.
        let total = sum_workload_costs(vec![(Some(1), &a), (Some(1), &b), (Some(2), &c)]).unwrap();
        assert_eq!(total.value, Some(7.0), "5.0 (once) + 2.0, not 5+5+2");
    }

    #[test]
    fn sum_workload_costs_never_deduplicates_entries_with_no_workload_id() {
        let a = ann(3.0, CostUnit::CostUnits);
        let b = ann(3.0, CostUnit::CostUnits);
        let total = sum_workload_costs(vec![(None, &a), (None, &b)]).unwrap();
        assert_eq!(total.value, Some(6.0));
    }

    #[test]
    fn sum_workload_costs_is_unavailable_when_any_distinct_entry_is_unavailable() {
        let known = ann(4.0, CostUnit::CostUnits);
        let unavailable = CostAnnotation::unavailable(CostUnit::CostUnits);
        let total = sum_workload_costs(vec![(None, &known), (None, &unavailable)]).unwrap();
        assert_eq!(total.value, None);
        assert_eq!(total.source, CostSource::Unavailable);
    }

    #[test]
    fn sum_workload_costs_rejects_mismatched_units() {
        let rate = ann(1.0, CostUnit::CostUnitsPerSecond);
        let total = ann(1.0, CostUnit::CostUnits);
        let err = sum_workload_costs(vec![(None, &rate), (None, &total)]).unwrap_err();
        assert_eq!(err.first, CostUnit::CostUnitsPerSecond);
        assert_eq!(err.second, CostUnit::CostUnits);
    }

    #[test]
    fn workload_cost_summary_computes_benefit_from_deduplicated_totals() {
        let baseline1 = ann(10.0, CostUnit::CostUnits);
        let selected1 = ann(3.0, CostUnit::CostUnits);
        let baseline2 = ann(10.0, CostUnit::CostUnits); // same shared node
        let selected2 = ann(3.0, CostUnit::CostUnits);
        let baseline3 = ann(4.0, CostUnit::CostUnits);
        let selected3 = ann(1.0, CostUnit::CostUnits);

        let entries = vec![
            (Some(1_u32), &baseline1, &selected1),
            (Some(1_u32), &baseline2, &selected2), // duplicate of node 1 — must not double count
            (Some(2_u32), &baseline3, &selected3),
        ];
        let summary = workload_cost_summary(entries, "test-v1").unwrap();
        assert_eq!(summary.baseline_cost.value, Some(14.0), "10 (once) + 4");
        assert_eq!(summary.selected_cost.value, Some(4.0), "3 (once) + 1");
        assert_eq!(summary.benefit.value, Some(10.0));
        assert_eq!(summary.benefit.benefit_ratio, Some(10.0 / 14.0));
    }
}
